-- Migration: Add pet photo AI guidance jobs
-- Backs the pet-owner "upload a photo, get AI guidance" feature (web + iOS
-- only). Guidance is generated by a vision-capable Ollama model that takes
-- ~3 minutes per response, far longer than any other synchronous call in
-- this codebase, so this table is the async job record: the server inserts
-- a 'pending' row on upload and responds immediately, the ML service (which
-- already writes rag_chunks/model_metadata directly) flips it to
-- 'processing' then 'completed'/'failed' from a background thread once
-- generation finishes, and the client polls this row by id. Not RAG-ingested
-- - this is unreviewed AI speculation about a photo, not a clinical record.

CREATE TABLE IF NOT EXISTS pet_photo_guidance (
  job_id         SERIAL PRIMARY KEY,
  pet_id         VARCHAR(50) NOT NULL REFERENCES pets(pet_id) ON DELETE CASCADE,
  customer_id    VARCHAR(50) NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
  photo_path     VARCHAR(500) NOT NULL,
  owner_note     TEXT,
  status         VARCHAR(20) NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  guidance_text  TEXT,
  error_message  TEXT,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pet_photo_guidance_customer ON pet_photo_guidance(customer_id);
CREATE INDEX IF NOT EXISTS idx_pet_photo_guidance_pet ON pet_photo_guidance(pet_id);

GRANT ALL ON TABLE pet_photo_guidance TO vetcarepro_admin;
GRANT USAGE, SELECT ON SEQUENCE pet_photo_guidance_job_id_seq TO vetcarepro_admin;
